Controllers/Aluno/AlunoViewController.cs
using AcademiaFacil.Data.DTO;
using AcademiaFacil.Data.Interfaces.Repository;
using AcademiaFacil.Models.Entidades;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace AcademiaFacil.Controllers.AlunoView;

public class AlunoViewController : Controller
{
    private IAlunoRepository _alunoRepository;
    private IMapper _mapper;

    public AlunoViewController(IAlunoRepository alunoRepository, IMapper mapper)
    {
        _alunoRepository = alunoRepository;
        _mapper = mapper;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Listagem()
    {
        List<Aluno> lista = _alunoRepository.GetAlunos();
        return View(lista);
    }

    public IActionResult Cadastro()
    {
        return View();
    }

    public IActionResult Deletar(int id)
    {
        _alunoRepository.DeleteAlunoById(id);
        return RedirectToAction("Listagem");
    }

    public IActionResult Editar(int id)
    {
        Aluno? aluno = _alunoRepository.GetAlunoById(id);
        return View(aluno);
    }

    public IActionResult AtualizarAluno(int id, UpdateAlunoDto updateAlunoDto)
    {
        if (ModelState.IsValid)
        {
            _alunoRepository.UpdateAluno(id, updateAlunoDto);
            return RedirectToAction("Listagem");
        }
        else
        {
            Aluno? aluno = _alunoRepository.GetAlunoById(id);
            return View("Editar", aluno);
        }
    }

    [HttpPost]
    public IActionResult Cadastrar(Aluno aluno)
    {
        if (ModelState.IsValid)
        {
            _alunoRepository.CreateAluno(aluno);
            return RedirectToAction("Listagem");
        }
        else
        {
            return View("Cadastro", aluno);
        }
    }
}

Controllers/Equipamento/EquipamentosController.cs
using AcademiaFacil.Data.Interfaces.Repository;
using AcademiaFacil.Models;
using AcademiaFacil.Models.Tipos;
using AcademiaFacil.Models.View;
using Microsoft.AspNetCore.Mvc;

namespace AcademiaFacil.Controllers.Equipamentos;

public class EquipamentosController : Controller
{
    private IEquipamentoRepository _equipamentoRepository;
    private IRelacaoCargasRepository _relacaoCargasRepository;

    public EquipamentosController(IEquipamentoRepository equipamentoRepository, IRelacaoCargasRepository relacaoCargasRepository)
    {
        _equipamentoRepository = equipamentoRepository;
        _relacaoCargasRepository = relacaoCargasRepository;
    }

    public IActionResult Index()
    {
        List<Equipamento> equipamentos = _equipamentoRepository.GetEquipamentos();
        return View(equipamentos);
    }

    public IActionResult Cadastro()
    {
        List<RelacaoCargas>? listaRelacaoCargas = _relacaoCargasRepository.GetRelacaoCargas();
        EquipamentoViewModel equipamentoViewModel = new EquipamentoViewModel(new Equipamento(), listaRelacaoCargas);
        return View(equipamentoViewModel);
    }

    public IActionResult Editar(int id)
    {
        Equipamento? equipamento = _equipamentoRepository.FindById(id);
        if (equipamento == null) return NotFound("Equipamento não encontrado.");
        List<RelacaoCargas>? listaRelacaoCargas = _relacaoCargasRepository.GetRelacaoCargas();
        EquipamentoViewModel equipamentoViewModel = new EquipamentoViewModel(equipamento, listaRelacaoCargas);
        return View(equipamentoViewModel);
    }

    public IActionResult Deletar(int id)
    {
        Equipamento? equipamento = _equipamentoRepository.FindById(id);
        if (equipamento == null) return NotFound("Equipamento não encontrado.");
        if (_equipamentoRepository.DeleteEquipamento(equipamento))
        {
            return RedirectToAction("Index");
        }
        else
        {
            return ValidationProblem("Erro ao excluir o equipamento.");
        }
    }

    public IActionResult EditarEquipamento(int id, Equipamento equipamento)
    {
        if (ModelState.IsValid)
        {
            _equipamentoRepository.UpdateEquipamento(id, equipamento);
            return RedirectToAction("Index");
        }
        else
        {
            var listaCargas = _relacaoCargasRepository.GetRelacaoCargas();
            EquipamentoViewModel equipamentoViewModel = new EquipamentoViewModel(equipamento, listaCargas);
            return View("Editar", equipamentoViewModel);
        }
    }

    [HttpPost]
    public IActionResult CadastrarEquipamento(Equipamento equipamento)
    {
        _equipamentoRepository.CreateEquipamento(equipamento);
        return RedirectToAction("Index");
    }

}

Controllers/Exercicio/ExerciciosViewController.cs
using AcademiaFacil.Configuration;
using AcademiaFacil.Data.Interfaces.Repository;
using AcademiaFacil.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace AcademiaFacil.Controllers.Exercicios;

public class ExerciciosViewController : Controller
{
    private IEquipamentoRepository _equipamentoRepository;
    private ITipoExercicioRepository _tipoExercicioRepository;
    private IExercicioRepository _exercicioRepository;
    private IRelacaoCargasRepository _relacaoCargasRepository;
    private ConfigPadroes configuracao;

    public ExerciciosViewController(IEquipamentoRepository equipamentoRepository, ITipoExercicioRepository tipoExercicioRepository, IExercicioRepository exercicioRepository, IOptions<ConfigPadroes> config, IRelacaoCargasRepository relacaoCargasRepository)
    {
        _equipamentoRepository = equipamentoRepository;
        _tipoExercicioRepository = tipoExercicioRepository;
        _exercicioRepository = exercicioRepository;
        configuracao = new ConfigPadroes();
        configuracao.NumeroRepeticoesPadrao = config.Value.NumeroRepeticoesPadrao;
        _relacaoCargasRepository = relacaoCargasRepository;
    }

    public IActionResult Index()
    {
        List<Exercicio> lista = _exercicioRepository.GetExercicios();
        PreencheViewBag();
        return View(lista);
    }

    public IActionResult Cadastrar()
    {
        PreencheViewBag();
        return View();
    }

    public IActionResult Editar(int id)
    {
        Exercicio? exercicio = _exercicioRepository.GetExerciciosPorId(id);
        PreencheViewBag();
        return View(exercicio);
    }

    public IActionResult EditarExercicio(Exercicio exercicio)
    {
        if (ModelState.IsValid)
        {
            _exercicioRepository.AtualizarExercicio(exercicio);
            return RedirectToAction("Index");
        }
        else
        {
            PreencheViewBag();
            return View("Editar", exercicio);
        }
    }

    public IActionResult Deletar(int id)
    {
        if (_exercicioRepository.DeletarExercicio(id))
        {
            return RedirectToAction("Index");
        }
        //TODO redirecionar para a página de erro
        return RedirectToAction("//");
    }

    [HttpPost]
    public IActionResult CadastrarExercicio(Exercicio exercicio)
    {
        if (ModelState.IsValid)
        {
            _exercicioRepository.CadastrarExercicio(exercicio);
            return RedirectToAction("Index");
        }
        else
        {
            PreencheViewBag();
            return View("Cadastrar", exercicio);
        }
    }

    private dynamic PreencheViewBag()
    {
        ViewBag.TiposExercicios = _tipoExercicioRepository.ListaTiposExercicio().Where(te => te.Ativo == true).ToList();
        ViewBag.Equipamentos = _equipamentoRepository.GetEquipamentos().Where(equip => equip.Ativo == true).ToList();
        ViewBag.RelacaoCargas = _relacaoCargasRepository.GetRelacaoCargas()!.Where(rc => rc.Ativo == true).ToList();
        ViewBag.RepeticaoPadrao = configuracao.NumeroRepeticoesPadrao;
        return ViewBag;
    }
}

Controllers/TiposExercicio/TiposExercicioViewController.cs
using AcademiaFacil.Data.Interfaces.Repository;
using AcademiaFacil.Models.Tipos;
using Microsoft.AspNetCore.Mvc;

namespace AcademiaFacil.Controllers.TiposExercicio
{
    public class TiposExercicioViewController : Controller
    {
        private ITipoExercicioRepository _tipoExercicioRepository;

        public TiposExercicioViewController(ITipoExercicioRepository tipoExercicioRepository)
        {
            _tipoExercicioRepository = tipoExercicioRepository;
        }

        public IActionResult Index()
        {
            List<TipoExercicio> listaTiposExercicio = _tipoExercicioRepository.ListaTiposExercicio();
            return View(listaTiposExercicio);
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            TipoExercicio tipoExercicio = _tipoExercicioRepository.BuscarTipoExercicioPorId(id)!;
            return View(tipoExercicio);
        }

        public IActionResult EditarTipoExercicio(TipoExercicio tipoExercicio)
        {
            if (ModelState.IsValid)
            {
                _tipoExercicioRepository.AtualizarTipoExercicio(tipoExercicio);
                return RedirectToAction("Index");
            }
            else
            {
                return View("Editar", tipoExercicio);
            }
        }

        public IActionResult Deletar(int id)
        {
            if (_tipoExercicioRepository.DeletarTipoExercicio(id))
            {
                return RedirectToAction("Index");
            }
            //TODO Retornar para a pagina de erro
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult CadastrarTipoExercicio(TipoExercicio tipoExercicio)
        {
            if (ModelState.IsValid)
            {
                _tipoExercicioRepository.CadastrarTipoExercicio(tipoExercicio);
                return RedirectToAction("Index");
            }
            else
            {
                return View("Cadastrar", tipoExercicio);
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AcademiaFacil</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AcademiaFacil.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand">Academia Fácil</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" role="button" asp-controller="AlunoView" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Alunos
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" role="button" asp-controller="AlunoView" asp-action="Cadastro">Novo Aluno</a></li>
                                <li><a class="dropdown-item" role="button" asp-controller="AlunoView" asp-action="Listagem">Cadastro de Alunos</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Equipamentos
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" role="button" asp-controller="Equipamentos" asp-action="Cadastro">Novo Equipamento</a></li>
                                <li><a class="dropdown-item" role="button" asp-controller="Equipamentos" asp-action="Index">Cadastro de Equipamentos</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Relação de Cargas
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" role="button" asp-controller="RelacaoCarga" asp-action="Cadastrar">Nova relação de carga</a></li>
                                <li><a class="dropdown-item" role="button" asp-controller="RelacaoCarga" asp-action="Index">Cadastro de relação de carga</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Exercícios
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" role="button" asp-controller="ExerciciosView" asp-action="Cadastrar">Novo exercício</a></li>
                                <li><a class="dropdown-item" role="button" asp-controller="ExerciciosView" asp-action="Index">Cadastro de exercício</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="dropdown-item" role="button" asp-controller="TiposExercicioView" asp-action="Index">Cadastro tipo de exercício</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="mb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AcademiaFacil - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_NavBar.cshtml
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar scroll</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Link
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Link</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>